build: Micronaut Framework to 3.5.4
micronaut-projects/micronaut-jms pull request #272
Opened 2022-08-03 19:36 UTC by sdelamo

- Micronaut Framework to 3.5.4
- Micronaut Test to 3.4.0
- Groovy to 3.0.12
- Spock 2.1

It seems @burtbeckwith had a stab at fixing the build.

https://github.com/micronaut-projects/micronaut-jms/pull/263

2022-08-11 22:03 UTC, wetted commented
This is a work in progress, with some tests still failing.

2022-08-12 15:40 UTC, wetted commented
this should satisfy the task for https://github.com/micronaut-projects/micronaut-core/issues/7720

2022-08-31 08:37 UTC, timyates requested changes

2022-08-31 08:37 UTC, timyates commented on buildSrc/src/main/groovy/io.micronaut.build.internal.jms-module.gradle
> +    runtimeOnly("javax.json:javax.json-api:1.1.4")
Should this be in the catalog?

2022-08-31 08:37 UTC, timyates commented on buildSrc/src/main/groovy/io.micronaut.build.internal.jms-tests.gradle
> +    runtimeOnly 'javax.json:javax.json-api:1.1.4'
Should this be in the catalog?

2022-08-31 08:37 UTC, timyates commented on gradle.properties
> +githubCoreBranch=3.5.x
Should this be 3.7.x?

2022-08-31 10:39 UTC, sdelamo commented on gradle.properties
> +githubCoreBranch=3.5.x
yes

2022-09-14 14:29 UTC, merged